In [3]:
import pandas as pd

users = pd.read_csv("../data/raw/users.csv")
users.head()

   user_id    name              email country           registration_date
0        1  User 1  user1@example.com      UK  2026-01-04 23:30:50.172483
1        2  User 2  user2@example.com      UK  2025-12-12 23:30:50.172497
2        3  User 3  user3@example.com      CA  2025-11-26 23:30:50.172500
3        4  User 4  user4@example.com      DE  2025-09-29 23:30:50.172502
4        5  User 5  user5@example.com      UK  2026-01-14 23:30:50.172503

In [4]:

print("users:", users.shape)
users.info()

users: (1000, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            1000 non-null   int64
 1   name               1000 non-null   object
 2   email              1000 non-null   object
 3   country            1000 non-null   object
 4   registration_date  1000 non-null   object
dtypes: int64(1), object(4)
memory usage: 39.2+ KB

In [5]:
users.head()

   user_id    name              email country           registration_date
0        1  User 1  user1@example.com      UK  2026-01-04 23:30:50.172483
1        2  User 2  user2@example.com      UK  2025-12-12 23:30:50.172497
2        3  User 3  user3@example.com      CA  2025-11-26 23:30:50.172500
3        4  User 4  user4@example.com      DE  2025-09-29 23:30:50.172502
4        5  User 5  user5@example.com      UK  2026-01-14 23:30:50.172503

In [6]:
artists = pd.read_csv("../data/raw/artists.csv")
tracks = pd.read_csv("../data/raw/tracks.csv")
listening_events = pd.read_csv("../data/raw/listening_events.csv")
subscriptions = pd.read_csv("../data/raw/subscriptions.csv")
payments = pd.read_csv("../data/raw/payments.csv")

print("artists:", artists.shape)
print("tracks:", tracks.shape)
print("listening_events:", listening_events.shape)
print("subscriptions:", subscriptions.shape)
print("payments:", payments.shape)

artists: (200, 4)
tracks: (5000, 5)
listening_events: (10000, 5)
subscriptions: (1000, 4)
payments: (1790, 6)

In [7]:
payments['amount'].sum()
successful = payments[payments["status"] == "success"]
successful.head()

,payment_id,user_id,payment_date,amount,payment_method,status
0,1,2,2025-12-02 23:30:50.180140,0.0,paypal,success
1,2,2,2026-01-01 23:30:50.180140,0.0,paypal,success
2,3,2,2026-01-31 23:30:50.180140,0.0,card,success
3,4,2,2026-03-02 23:30:50.180140,0.0,card,success
4,5,2,2026-04-01 23:30:50.180140,0.0,paypal,success

In [8]:
successful['month'] = pd.to_datetime(successful['payment_date']).dt.to_period('M')
mrr = successful.groupby('month')['amount'].sum()
mrr

/var/folders/87/7k95tvt54f99ck9dm1w6c_j40000gp/T/ipykernel_46029/31957260.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  successful['month'] = pd.to_datetime(successful['payment_date']).dt.to_period('M')

month
2025-04     44.96
2025-05    259.75
2025-06    424.62
2025-07    679.39
2025-08    699.38
2025-09    664.42
2025-10    689.39
2025-11    739.34
2025-12    654.40
2026-01    684.38
2026-02    649.40
2026-03    699.35
2026-04    619.41
2026-05    354.65
2026-06    204.80
2026-07    124.88
2026-08     59.94
2026-09     19.98
Freq: M, Name: amount, dtype: float64